[build-system]
requires = [
    "setuptools>=46.4.0",
    "wheel",
    "toml",
    "pip-tools",
    "sqlalchemy",
]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
requires = [
    "mypy",
    "pylint",
    "pytest",
    "coverage>=5.0.3",
]